default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

development:
  <<: *default
  database: forecastly_development

test:
  <<: *default
  database: forecastly_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
